[build]
  command = "dart pub global activate jaspr_cli && jaspr build"
  publish = "build/jaspr"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  DART_VERSION = "stable"
